### PR TITLE
MR-3177 State sees relevant yes/no provision options and citations for CHIP-Only

### PR DESCRIPTION
**Pull request by haworku**
## Summary

Adjusted yes/no logic to have a different set of provisions for CHIP only (six provisions related to risks and payments are simply not included or displayed for CHIP subs). Also made copy changes that were in Figma to the MLR references.

#### Related issues
https://qmacbis.atlassian.net/browse/MR-3177 

#### Test cases covered
New tests
- ` shows correct validations for CHIP only submissions`
-  `does not allow setting risk related or payments provisions for CHIP only submissions`. 
- `removes any risk related modified provisions from CHIP submission and submits successfully`
- `sorts amended provisions correctly and removes risk provisions from unmodified list for CHIP amendment`

## QA guidance
 
I suggest testing CHIP and non CHIP modified provisions behaviors.

### CODE REVIEW

**Comment by haworku** [comment]
As per backlog grooming today, sounds like loosening the string matching won't be the best approach anymore in tests since we are going to have similar provisions with slightly different MLR references for base contract provisions. I will add a commit that switches to using string literaly again.

**Comment by haworku** [comment]
I will push another commit to further refactor tests. Was hoping to simplify tests and what breaks tests with provisions MLR references changing. But aafter backlog grooming today sounds like we are going to have more logic around provisions with different MLR references so testing for full string is still needed.

**Review by JasonLin0991 — APPROVED** [review]
On the review and submit page, would it make sense display some kind of notice for `modified provisions` section that some of them are not answered? Like how `risk-based` and `population covered` fields are done.

You can get to that state by: 
- Unlocking CHIP only submission from before the provision changes 

OR 

- Submit a new CHIP-only submission and unlock it
- Change the submission to Medicaid and `Save as draft`

When submitting you will be notified that the submission is missing data, but it doesn't say what information.

Other than that, the rest looks good.

**Comment by haworku** [comment]
@JasonLin0991  Thank you!  Could you give me more detail about 1. the error we are seeing in the network tab - what error message the API is returning 2. If the submissions tested were "base contracts" or "amendments to base contracts". 

FYI the missing data error behavior should already  be built in for modified provisions. I'm seeing it too 🤔 . I think you are finding some other bug that needs to be addressed but I can't replicate right now.

**Comment by JasonLin0991** [comment]
> @JasonLin0991 Thank you! Could you give me more detail about 1. the error we are seeing in the network tab - what error message the API is returning 2. If the submissions tested were "base contracts" or "amendments to base contracts".
> 
> FYI the missing data error behavior should already be built in for modified provisions. I'm seeing it working fine on my end 🤔 . I think you are finding some other bug that needs to be addressed but I can't replicate right now.

Here is the error that comes back from the API

<details>
<summary>Error Response</summary>

```json
{
   "errors":[
      {
         "message":"formData is missing required contract fields",
         "locations":[
            {
               "line":2,
               "column":3
            }
         ],
         "path":[
            "submitHealthPlanPackage"
         ],
         "extensions":{
            "message":"formData is missing required contract fields",
            "code":"BAD_USER_INPUT",
            "exception":{
               "stacktrace":[
                  "UserInputError: formData is missing required contract fields",
                  "    at Object.submitHealthPlanPackage (/var/task/src/handlers/apollo_gql.js:1:147917)"
               ]
            }
         }
      }
   ],
   "data":null
}
```

</details>

Sorry, should have specified a bit more. You should see errors switching from `CHIP-Only`-`Contract`-`Amendment` to `Medicaid` or `Medicaid and Chip` and `Contract`-`Amendment`

You can get to that state by:

- Unlocking CHIP-only submission from before the provision changes
- Switching to `Medicaid` or `Medicaid and Chip` and `Contract`-`Amendment`
- Save as draft
- Go back to the submission and submit.

OR

- Submit a new CHIP-only submission and unlock it.
- Switch to `Medicaid` or `Medicaid and Chip`-`Contract`-`Amendment`
- Save as draft
- Go back to the submission and submit.

**Comment by haworku** [comment]
@JasonLin0991 Ah, I see it now thank you that detail helped.  I will fix this.

**Pull request merged**
