### PR TITLE
MCR-4255: do not display NEW tag on initial submissions

### PR DESCRIPTION
**Pull request by pearl-truss**
## Summary

This is small PR for ensuring that the 'NEW' tag doesn't appear on the submission summary for initial submissions

This also fixes an underlying bug we had with 'date added' being displayed on initial submission

#### Related issues
https://jiraent.cms.gov/browse/MCR-4255

#### Screenshots

Initial submission (no new tag)
Screenshot 2024-07-09 at 4 37 16 PM

After unlock and resubmitting with additional document (new tag present)
Screenshot 2024-07-09 at 4 38 11 PM

#### Test cases covered

- RateDetailsSummarySection - NEW tag not displayed on initial submission
- ContractDetailsSummarySection - NEW tag not displayed on initial submission

## QA guidance

- Create a new contract and rate submission 
- Upload documents and fill out details and submit 
- Log in as a CMS user and view submission just made
- Notice on the submission summary page none of the documents on the initial submission are marked as "new"

### CODE REVIEW

**Review by haworku — APPROVED** [review]
Yes, this makes sense.

**Review by JasonLin0991 — COMMENTED** [review]
I double checked with Kelsey, the date added should appear on initial submissions.

**Comment by pearl-truss** [comment]
> I double checked with Kelsey, the date added should appear on initial submissions.

Oh interesting, thanks for double checking! There's a comment in uploadedDocumentstable that says

// canDisplayDateForDocument -  guards against passing in null or undefined to dayjs
// don't display on new initial submission

That I'll update

**Comment by haworku** [comment]
@JasonLin0991 @pearl-truss  Sorry for confusion here.  Re: `don't display on new initial submission`  -- its not supposed to display on review and submit on initial submission (so i guess "prior to the initial submission" would have been much more accurate comment). The dates should display once that document has been submitted both on review submit and submission summary

**Pull request merged**
