### PR TITLE
[MCR-2613] Edit MC-CRS number

### PR DESCRIPTION
**Pull request by pearl-truss**
## Summary

to be merged after https://github.com/Enterprise-CMCS/managed-care-review/pull/1996

This PR adds test relevant to editing a MC-CRS record number

#### Related issues

https://qmacbis.atlassian.net/browse/MCR-2613

#### Screenshots

Screenshot 2023-10-25 at 10 57 54 AM
Screenshot 2023-10-25 at 10 58 02 AM

#### Test cases covered

- MC-CRS id pre-populates on the text field if the `mccrsID` is set
- Displays the Edit MC-CRS id link

## QA guidance

- Sign in as a CMS user 
- Click on a submission and add a MC-CRS id. Once back on the submission summary page, click Edit MC-CRS number and you should be taken back to the text field with the previous value pre-populated

### CODE REVIEW

**Comment by pearl-truss** [comment]
I didn't include a fix for the flicker that Jason [mentioned](https://github.com/Enterprise-CMCS/managed-care-review/pull/1996#discussion_r1370730560) because I'm not able to reproduce it locally, only through the deployed review app which will take additional time to verify any changes added for fixing the bug. 

I created a bug ticket here: https://qmacbis.atlassian.net/browse/MCR-3582

**Comment by pearl-truss** [comment]
> I didn't include a fix for the flicker that Jason [mentioned](https://github.com/Enterprise-CMCS/managed-care-review/pull/1996#discussion_r1370730560) because I'm not able to reproduce it locally, only through the deployed review app which will take additional time to verify any changes added for fixing the bug.
> 
> I created a bug ticket here: https://qmacbis.atlassian.net/browse/MCR-3582

We might [not need](https://cmsgov.slack.com/archives/C014CRU197U/p1698252419829969) a feature flag for this work, if that's the case I will mark the bug ticket as not doing and remove the flag from LD

**Review by macrael — APPROVED** [review]

**Review by JasonLin0991 — COMMENTED** [review]
Sorry! I missed a few things from my review of this [PR](https://github.com/Enterprise-CMCS/managed-care-review/pull/1996).

- Cannot add or edit MC-CRS ID on Unlocked submissions, and the error banner should be consistent with the other pages.
Screenshot 2023-10-25 at 5 37 55 PM

- Adding or editing MC-CRS ID that include spaces are trimmed in the URL but not elsewhere; when going back to edit that ID it shows `NaN` in the input.

**Comment by pearl-truss** [comment]
> > Sorry! I missed a few things from my review of this [PR](https://github.com/Enterprise-CMCS/managed-care-review/pull/1996).
> > 
> > * Cannot add or edit MC-CRS ID on Unlocked submissions
> > * The error banner should be consistent with the other pages.
> > * Adding or editing MC-CRS ID that include spaces are trimmed in the URL but not elsewhere; when going back to edit that ID it shows `NaN` in the input.
> 
> Thanks, I fixed the 2nd and 3rd items. Good catch on the first, the expected behavior for unlocked submissions wasn't specified in the AC so I've asked design and product for clarification

Product and design said they should be able to add and edit for unlocked submissions so I updated the `updateContract` resolver

**Pull request merged**
